### ISSUE TITLE
Evitar selectores de etiquetas

### ISSUE THREAD

**Issue by nasivuela** [Adalab/d-s1-evaluacion-intermedia-raquelv85#4]
Buen trabajo, casi todos los selectores son de tipo clase, pero se nos ha colado alguno de tipo etiqueta, como `img`.

Si mañana la web tiene otra imagen la liamos...

**Comment by raquelv85** [comment]
Buenas Nasiba, yo le di clase a img (img-adalab), lo que hice fue darle un estilo general a todas las imagenes para que siempre sean display: block,  ¿No es buena practica hacer eso?

**Comment by nasivuela** [comment]
Igual mañana tenemos otra imagen en la página y si no es block, si no inline o inline-block, mal asunto. Igual con el header, nada garantiza que otro header vaya a tener el mismo color de fondo.
Habrá casos donde si podamos hacer esto, cuando venga definido en una guía de estilos, o si no la hay, cuando observemos una pauta en el diseño muy muy clara. Por ejemplo, todos los títulos principales (h1) van a ser rosas, con un tamaño x y unos márgenes x. Incluso aquí si no tenemos seguridad sobre si mañana puede llegar una variante desde diseño, sería mejor tener una clase y usarla en todas las etiquetas h1.

**Comment by nasivuela** [comment]
Reabro para ver si nos libramos de eso selector de etiqueta `header`.

Pero muy buen trabajo @raquelv85 !!! You got it.

![](https://media.giphy.com/media/100YmlniUkSv84/giphy.gif)
